server:
  port: 8888
  
logging:
  level:
    org.springframework.cloud: 'DEBUG' 

spring:
  security:
    user:
      password: password
  cloud:
    config:
      server:
        git:
          uri: https://github.com/benchacko/spring-config-server.git